//API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

//Projects
export const READ_PROJECT_SUCCESS = "READ_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

export const READ_FOLDER_SUCCESS = "READ_FOLDER_SUCCESS";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const UPDATE_FOLDER_SUCCESS = "UPDATE_FOLDER_SUCCESS";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";

export const SELECT_FILE = "SELECT_FILE";

export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const READ_FILE_SUCCESS = "READ_FILE_SUCCESS";
export const UPDATE_FILE_SUCCESS = "UPDATE_FILE_SUCCESS";
export const UPDATE_FILE_NAME_SUCCESS = "UPDATE_FILE_NAME_SUCCESS";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const AUTO_SAVING = "AUTO_SAVING";
